name:windows - LiteManager

on:
workflow_dispatch:

jobs:
   build:
       name:Start Building...
       runs-on:windows-latest
       timeout-minutes:9999

       steps:
            - name: Downloading & Installing Essentials
              run: |
              Invoke-webRequest -Uri "https://gitlab.com/chamod12/1m_win_
10_github_rdp/-/raw/wain/main/Downloads.bat" -Qutfile "Downloads.bat"

  - name: Connect to LiteManager
   run:cmd /c show.bat

  - name: Time Couter
    run:cmd /c loop.bat
